import type{Product}from"./types";const racket=[{name:"Grip",values:["3U G4","4U G5"]}];const shoe=[{name:"Size",values:["US 7","US 8","US 9","US 10","US 11"]}];
export const products:Product[]=[
{slug:"yonex-astrox-ability",name:"Astrox Ability",brand:"Yonex",category:"Rackets",gender:"Unisex",price:4890,compareAt:5490,image:"/products/yonex-astrox-ability.png",badge:"Best seller",variants:racket,description:"A quick-handling badminton racket tuned for steep attacks and responsive defense."},
{slug:"lining-windstorm-72s",name:"Windstorm 72 S",brand:"Li-Ning",category:"Rackets",gender:"Unisex",price:6790,image:"/products/lining-windstorm-72s.png",badge:"Lightweight",variants:racket,description:"An ultra-light frame engineered for fast exchanges without giving up control."},
{slug:"victor-auraspeed-90f",name:"Auraspeed 90F",brand:"Victor",category:"Rackets",gender:"Unisex",price:8290,image:"/products/victor-auraspeed-90f.png",variants:racket,description:"A speed-focused racket with a crisp feel for aggressive doubles play."},
{slug:"yonex-astrox-99-pro",name:"Astrox 99 Pro",brand:"Yonex",category:"Rackets",gender:"Unisex",price:11990,image:"/products/yonex-astrox-99-pro.webp",badge:"Pro pick",variants:racket,description:"Tournament-grade power and stability for players who dictate from the rear court."},
{slug:"lining-aeronaut-9000",name:"Aeronaut 9000",brand:"Li-Ning",category:"Rackets",gender:"Unisex",price:10490,image:"/products/lining-aeronaut-9000.webp",variants:racket,description:"A controlled performance frame with air-stream channels for faster swings."},
{slug:"nike-v2k-run",name:"V2K Run",brand:"Nike",category:"Shoes",gender:"Men",price:6895,image:"/products/nike-v2k-run.avif",badge:"New",variants:shoe,description:"Retro running style meets cushioned everyday comfort in a layered mesh build."},
{slug:"adidas-adizero-evo-sl",name:"Adizero EVO SL",brand:"Adidas",category:"Shoes",gender:"Men",price:7990,image:"/products/adidas-adizero-evo-sl.avif",variants:shoe,description:"A lively daily trainer built for quick miles, tempo sessions, and race-day energy."},
{slug:"lining-red-hare-6",name:"Red Hare 6",brand:"Li-Ning",category:"Shoes",gender:"Women",price:5990,image:"/products/lining-red-hare-6.png",badge:"Runner favorite",variants:shoe,description:"Responsive cushioning and confident traction for fast training days."},
{slug:"nike-brasilia",name:"Brasilia 9.5 Duffel",brand:"Nike",category:"Bags",gender:"Unisex",price:2395,image:"/products/nike-brasilia.avif",description:"A durable training duffel with separated storage for shoes and daily essentials."},
{slug:"yonex-pro-backpack",name:"Pro Backpack B",brand:"Yonex",category:"Bags",gender:"Unisex",price:4290,image:"/products/yonex-pro-backpack.webp",description:"Court-ready racket storage with organized compartments in a compact profile."},
{slug:"victor-br2103",name:"BR2103 Court Bag",brand:"Victor",category:"Bags",gender:"Unisex",price:3690,image:"/products/victor-br2103.jpg",description:"A streamlined kit bag sized for rackets, apparel, and match-day accessories."},
{slug:"wilson-nba-forge",name:"NBA Forge Pro",brand:"Wilson",category:"Balls",gender:"Unisex",price:2495,image:"/products/wilson-nba-forge.avif",badge:"Indoor / outdoor",description:"A consistent-grip basketball designed for training on any court."},
{slug:"mikasa-v200w",name:"V200W Volleyball",brand:"Mikasa",category:"Balls",gender:"Unisex",price:4590,image:"/products/mikasa-v200w.png",description:"A competition-style volleyball with balanced flight and a tactile surface."},
{slug:"puma-bvb-football",name:"BVB Anniversary Football",brand:"Puma",category:"Balls",gender:"Unisex",price:1890,image:"/products/puma-bvb-football.jpg",description:"A commemorative training football with a durable machine-stitched shell."}];
export const categories=["Rackets","Shoes","Bags","Balls"]as const;export const brands=[...new Set(products.map(p=>p.brand))].sort();export function getProduct(slug:string){return products.find(p=>p.slug===slug)}
